version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "7000:7000"
    networks:
      - app_network

  leaderboard:
    build: ./leaderboard
    ports:
      - "7001:7001"
    networks:
      - app_network

  frontend:
    build: ./frontend
    ports:
      - "7002:3000"
    depends_on:
      - backend
      - leaderboard
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
